# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trafficUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(-6, -5, 791, 571))
        self.videoLabel.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.locationComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.locationComboBox.setGeometry(QtCore.QRect(210, 570, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.locationComboBox.setFont(font)
        self.locationComboBox.setObjectName("locationComboBox")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.textSelectLocation = QtWidgets.QLabel(self.centralwidget)
        self.textSelectLocation.setGeometry(QtCore.QRect(20, 570, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textSelectLocation.setFont(font)
        self.textSelectLocation.setObjectName("textSelectLocation")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(790, 70, 371, 531))
        self.listWidget.setObjectName("listWidget")
        self.textHistory = QtWidgets.QLabel(self.centralwidget)
        self.textHistory.setGeometry(QtCore.QRect(940, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.textHistory.setFont(font)
        self.textHistory.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textHistory.setObjectName("textHistory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.locationComboBox.setItemText(0, _translate("MainWindow", "Lê Văn Việt"))
        self.locationComboBox.setItemText(1, _translate("MainWindow", "Võ Văn Ngân"))
        self.locationComboBox.setItemText(2, _translate("MainWindow", "Võ Văn Kiệt"))
        self.locationComboBox.setItemText(3, _translate("MainWindow", "Hai Bà Trưng"))
        self.locationComboBox.setItemText(4, _translate("MainWindow", "Võ Chí Công"))
        self.textSelectLocation.setText(_translate("MainWindow", "Select location"))
        self.textHistory.setText(_translate("MainWindow", "History"))
